#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#   Este nodo se suscribe a una imagen de ROS, la convierte en una matriz de
#   OpenCV y la muestra en pantalla
#

import rospy
import cv2
import numpy as np
from sensor_msgs.msg import Image
from cv_bridge import CvBridge

class Cam(object):
    def __init__(self, topic_name="camera/rgb/image_raw"):
        self.bridge = CvBridge()
        self.image = np.zeros((10,10))
        isub = rospy.Subscriber(topic_name, Image, self.image_callback)

    def image_callback(self, img):
        self.image = self.bridge.imgmsg_to_cv2(img, "bgr8")

    def get_image(self):
        return self.image

# Inicializar el nodo de ROS
rospy.init_node('camera_node')

# Objeto que se suscribe al tópico de la cámara
topic_name = "/camera/rgb/image_raw"
cam = Cam(topic_name)

# Tópico para publicar una imagen de salida
topic_pub = 'image_out'
pubimg = rospy.Publisher(topic_pub, Image, queue_size=10)

# Morph
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (15,15))

# Frecuencia del bucle principal
freq = 10
rate = rospy.Rate(freq)
flag = False
# Bucle principal
while not rospy.is_shutdown():
    # Obtener la imagen del tópico de ROS en formato de OpenCV
    I = cam.get_image()
    if flag:
        # Convertir BGR a HSV
        Ihsv = cv2.cvtColor(I, cv2.COLOR_BGR2HSV)
        
        # Red lower mask (0-10)
        lower_red = np.array([0,50,50])
        upper_red = np.array([5,255,255])
        mask0 = cv2.inRange(Ihsv, lower_red, upper_red)

        # Red upper mask (170-180)
        lower_red = np.array([175,50,50])
        upper_red = np.array([180,255,255])
        mask1 = cv2.inRange(Ihsv, lower_red, upper_red)
        
        # Blue mask
        lower_blue = np.array([113,140,0])
        upper_blue = np.array([140,255,180])
        mask2 = cv2.inRange(Ihsv, lower_blue, upper_blue)
        
        # gold mask
        #lower_yellow = np.array([15,50,50])
        #upper_yellow = np.array([25,255,255])
        #mask3 = cv2.inRange(Ihsv, lower_yellow, upper_yellow)

        # join beer colors masks
        #beerMask = mask2+mask3
        #beerMask = cv2.morphologyEx(beerMask, cv2.MORPH_CLOSE, kernel)
        #beerMask = cv2.dilate(beerMask, kernel, iterations=2)

        # Joint masks
        canMask = mask0+mask1+mask2
        canMask = cv2.morphologyEx(canMask, cv2.MORPH_CLOSE, kernel)
        canMask = cv2.dilate(canMask, kernel, iterations=2)
        #canMask = cv2.morphologyEx(canMask, cv2.MORPH_OPEN, kernel)
        #canMask = cv2.dilate(canMask, kernel, iterations=2)
        canImg = cv2.bitwise_and(I,I,mask = canMask)

        # Mostrar la imagen
        cv2.imshow("Imagen", canImg)

    # Esperar al bucle para actualizar
    cv2.waitKey(1)
    # Opcional: publicar la imagen de salida como tópico de ROS
    #pubimg.publish(cam.bridge.cv2_to_imgmsg(I))
    flag = True
    rate.sleep()

cv2.destroyAllWindows()